[package]
name = "subspace_assignment"
version = "0.1.0"
authors = ["aljo242 <amj92@pitt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.12.0"